name: Build and Deploy from Dev Branch

on:
  push:
    branches:
      - main  # Only trigger on push to dev branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Upload JAR as artifact (optional)
        uses: actions/upload-artifact@v2.3.1
        with:
          name: app-jar
          path: target/*.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v2.3.1
        with:
          name: app-jar
          path: jar/

      - name: Deploy to server via SCP
        run: |
          scp -i ~/.ssh/id_rsa jar/*.jar root@103.174.50.131:/root/OpsCICD/executables/
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: (Optional) Restart server process
        run: |
          ssh -i ~/.ssh/id_rsa root@103.174.50.131 'sudo systemctl restart your-app.service'
