name: Build and Deploy from Dev Branch

on:
  push:
    branches:
      - main  # Make sure this matches your branch name

permissions:
  contents: read  # Required for downloading GitHub-hosted actions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -DskipTests

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code (optional but safe)
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 103.174.50.131 >> ~/.ssh/known_hosts

      - name: Deploy to server via SCP
        run: |
          scp -i ~/.ssh/id_rsa /jar*.jar root@103.174.50.131:/root/OpsCICD/executables/

      - name: Restart server process (optional)
        run: |
          ssh -i ~/.ssh/id_rsa root@103.174.50.131 'sudo systemctl restart your-app.service'
