name: Build and Deploy from Dev Branch

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -DskipTests


  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Run remote command using sshpass
              run: |
                sshpass -p "${{ secrets.SERVER_PASSWORD }}" ssh -o StrictHostKeyChecking=no root@103.174.50.131 'mkdir -p /root/OpsCICD/test-folder'
